/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package optimizadordemezclas;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author Luigi
 */
public class Inicio extends javax.swing.JPanel {

    
    //private String[] estado;
    private String path;
    private JLabel[] infBas;
    private JLabel[] dif1x2;
    private JLabel[] infProd;
    private JLabel[] form;
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        //Establecemos el directorio para referencias futuras
        path = System.getProperty("user.dir");
        
        //Creamos y llenamos el arreglo que contendrá las etiquetas relevantes a los productos
        infProd = new JLabel[12];
        
        infProd[0] = txtViscoCin;
        infProd[1] = txtViscoDin;
        infProd[2] = txtColor;
        infProd[3] = txtVola;
        infProd[4] = txtViscoCin1;
        infProd[5] = txtViscoDin1;
        infProd[6] = txtColor1;
        infProd[7] = txtVola1;
        infProd[8] = txtViscoCin2;
        infProd[9] = txtViscoDin2;
        infProd[10] = txtColor2;
        infProd[11] = txtVola2;
        
        //Creamos y llenamos el arreglo que contendrá las etiquetas relevantes a la tabla dif1x2
        dif1x2 = new JLabel[4];
        
        dif1x2[0] = txtx1Form;
        dif1x2[1] = txtx1Prog;
        dif1x2[2] = txtx2Form;
        dif1x2[3] = txtx2Prog;
       
        //Creamos y llenamos el arreglo que contendrá las etiquetas relevantes a los básicos
        infBas = new JLabel[12];
        
        infBas[0] = txtNomBa1;
        infBas[1] = txBa1;
        infBas[2] = txtFracMa1;
        infBas[3] = txCUBa1;
        infBas[4] = txCanBa1;
        infBas[5] = txCpBa1;
        infBas[6] = txtNomBa2;
        infBas[7] = txBa2;
        infBas[8] = txtFracMa2;
        infBas[9] = txCUBa2;
        infBas[10] = txCanBa2;
        infBas[11] = txCpBa2;
        
        //Creamos y llenamos el arreglo que contendrá las etiquetas relevantes a la formulación
        form = new JLabel[15];
        
        form[0] = txtCodProd;
        form[1] = txLinea;
        form[2] = txGrado;
        form[3] = txB1n;
        form[4] = txB1c;
        form[5] = txB2n;
        form[6] = txB2c;
        form[7] = txB1x;
        form[8] = txB2x;
        form[9] = txTemp;
        form[10] = txVol;
        form[11] = txCst;
        form[12] = txColor;
        form[13] = txCp;
        form[14] = txCpM1;
        
        ArrayList<String> itemsCombo = Utils.generaCol("formulaciones.csv", 3);
        Collections.sort(itemsCombo);
        
        for(String s : itemsCombo)
            combo.addItem(s);
        
        //Esconde label avio
        txAviso.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCalcula = new javax.swing.JButton();
        txCpM = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        txAviso = new javax.swing.JLabel();
        lbDemanda = new javax.swing.JLabel();
        txtDemanda = new javax.swing.JTextField();
        rbFroz = new javax.swing.JRadioButton();
        txtCodProd = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txLinea = new javax.swing.JLabel();
        txB1n = new javax.swing.JLabel();
        txB1c = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txB1x = new javax.swing.JLabel();
        txCst = new javax.swing.JLabel();
        txTemp = new javax.swing.JLabel();
        txCp = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txGrado = new javax.swing.JLabel();
        txB2n = new javax.swing.JLabel();
        txB2c = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txB2x = new javax.swing.JLabel();
        txColor = new javax.swing.JLabel();
        txVol = new javax.swing.JLabel();
        txCpM1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txBa1 = new javax.swing.JLabel();
        txBa2 = new javax.swing.JLabel();
        txCUBa1 = new javax.swing.JLabel();
        txCUBa2 = new javax.swing.JLabel();
        txCanBa1 = new javax.swing.JLabel();
        txCanBa2 = new javax.swing.JLabel();
        txCpBa1 = new javax.swing.JLabel();
        txCpBa2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        txCostMez2 = new javax.swing.JLabel();
        txtValFin = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txCostMez1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        txtNomBa1 = new javax.swing.JLabel();
        txtNomBa2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtInfoBas1 = new javax.swing.JLabel();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        txtViscoCin = new javax.swing.JLabel();
        txtViscoDin = new javax.swing.JLabel();
        txtColor = new javax.swing.JLabel();
        txtVola = new javax.swing.JLabel();
        txtViscoCin1 = new javax.swing.JLabel();
        txtViscoDin1 = new javax.swing.JLabel();
        txtColor1 = new javax.swing.JLabel();
        txtVola1 = new javax.swing.JLabel();
        txtViscoCin2 = new javax.swing.JLabel();
        txtViscoDin2 = new javax.swing.JLabel();
        txtColor2 = new javax.swing.JLabel();
        txtVola2 = new javax.swing.JLabel();
        jSeparator26 = new javax.swing.JSeparator();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        txtFracMa1 = new javax.swing.JLabel();
        txtFracMa2 = new javax.swing.JLabel();
        txtViscoCin3 = new javax.swing.JLabel();
        txtViscoCin4 = new javax.swing.JLabel();
        txtViscoCin5 = new javax.swing.JLabel();
        txtInfoBas2 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jSeparator27 = new javax.swing.JSeparator();
        jSeparator28 = new javax.swing.JSeparator();
        jSeparator29 = new javax.swing.JSeparator();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jSeparator31 = new javax.swing.JSeparator();
        jSeparator32 = new javax.swing.JSeparator();
        txtx1Form = new javax.swing.JLabel();
        txtx1Prog = new javax.swing.JLabel();
        txtx2Form = new javax.swing.JLabel();
        txtx2Prog = new javax.swing.JLabel();
        jSeparator33 = new javax.swing.JSeparator();
        jSeparator34 = new javax.swing.JSeparator();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jSeparator30 = new javax.swing.JSeparator();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jSeparator35 = new javax.swing.JSeparator();
        combo1 = new javax.swing.JComboBox<>();
        txtInfoBas3 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(36, 47, 65));
        setForeground(new java.awt.Color(36, 47, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Código de producto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 110, -1, -1));

        btnCalcula.setText("Calcular");
        btnCalcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        txCpM.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCpM.setForeground(new java.awt.Color(204, 204, 204));
        txCpM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimizadordemezclas/logo.png"))); // NOI18N
        jPanel1.add(txCpM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        combo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboKeyPressed(evt);
            }
        });
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        txAviso.setText("Calculando...");
        txAviso.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txAvisoComponentShown(evt);
            }
        });
        jPanel1.add(txAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 80, 20));

        lbDemanda.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lbDemanda.setText("Ingrese la demanda");
        jPanel1.add(lbDemanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));
        jPanel1.add(txtDemanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 100, -1));

        rbFroz.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rbFroz.setText("Precio Frozen");
        rbFroz.setOpaque(false);
        jPanel1.add(rbFroz, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 980));

        txtCodProd.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtCodProd.setForeground(new java.awt.Color(204, 204, 204));
        txtCodProd.setText("NA");
        add(txtCodProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 700, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Código del producto:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 670, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("CP sin mejorador:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 880, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Línea:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 670, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("B1 Código:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 740, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("B1 Nombre:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 740, -1, -1));

        txLinea.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txLinea.setForeground(new java.awt.Color(204, 204, 204));
        txLinea.setText("NA");
        txLinea.setName("txLinea"); // NOI18N
        add(txLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 700, -1, -1));

        txB1n.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txB1n.setForeground(new java.awt.Color(204, 204, 204));
        txB1n.setText("NA");
        add(txB1n, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 770, -1, -1));

        txB1c.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txB1c.setForeground(new java.awt.Color(204, 204, 204));
        txB1c.setText("NA");
        add(txB1c, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 770, -1, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("B1 X1:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 810, -1, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("cSt a 100°C:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 880, -1, -1));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Temp para CCS:");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 810, -1, -1));

        txB1x.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txB1x.setForeground(new java.awt.Color(204, 204, 204));
        txB1x.setText("NA");
        add(txB1x, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 840, -1, -1));

        txCst.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCst.setForeground(new java.awt.Color(204, 204, 204));
        txCst.setText("NA");
        add(txCst, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 910, -1, -1));

        txTemp.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txTemp.setForeground(new java.awt.Color(204, 204, 204));
        txTemp.setText("NA");
        add(txTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 840, -1, -1));

        txCp.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCp.setForeground(new java.awt.Color(204, 204, 204));
        txCp.setText("NA");
        add(txCp, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 910, -1, -1));

        jLabel32.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 204, 204));
        jLabel32.setText("CP con mejorador:");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 880, -1, -1));

        jLabel33.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 204));
        jLabel33.setText("Grado:");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 670, -1, -1));

        jLabel34.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 204, 204));
        jLabel34.setText("B2 Código:");
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 740, -1, -1));

        jLabel35.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 204, 204));
        jLabel35.setText("B2 Nombre:");
        add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 740, -1, -1));

        txGrado.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txGrado.setForeground(new java.awt.Color(204, 204, 204));
        txGrado.setText("NA");
        add(txGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 700, -1, -1));

        txB2n.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txB2n.setForeground(new java.awt.Color(204, 204, 204));
        txB2n.setText("NA");
        add(txB2n, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 770, -1, -1));

        txB2c.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txB2c.setForeground(new java.awt.Color(204, 204, 204));
        txB2c.setText("NA");
        add(txB2c, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 770, -1, -1));

        jLabel39.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 204, 204));
        jLabel39.setText("B2 X2:");
        add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 810, -1, -1));

        jLabel40.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 204, 204));
        jLabel40.setText("Volatilidad");
        add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 430, -1, -1));

        jLabel41.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 204, 204));
        jLabel41.setText("Volatilidad:");
        add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 810, -1, -1));

        txB2x.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txB2x.setForeground(new java.awt.Color(204, 204, 204));
        txB2x.setText("NA");
        add(txB2x, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 840, -1, -1));

        txColor.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txColor.setForeground(new java.awt.Color(204, 204, 204));
        txColor.setText("NA");
        add(txColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 910, -1, -1));

        txVol.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txVol.setForeground(new java.awt.Color(204, 204, 204));
        txVol.setText("NA");
        add(txVol, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 840, -1, -1));

        txCpM1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCpM1.setForeground(new java.awt.Color(204, 204, 204));
        txCpM1.setText("NA");
        add(txCpM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 910, -1, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 650, 1310, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 710, 250, -1));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 650, 10, 60));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Formulación");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 660, -1, -1));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 250, -1));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 10, 80));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Resultados");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Cantidad (kg)");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 70, -1, -1));

        txBa1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txBa1.setForeground(new java.awt.Color(204, 204, 204));
        txBa1.setText("NA");
        add(txBa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, -1, -1));

        txBa2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txBa2.setForeground(new java.awt.Color(204, 204, 204));
        txBa2.setText("NA");
        add(txBa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, -1, -1));

        txCUBa1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCUBa1.setForeground(new java.awt.Color(204, 204, 204));
        txCUBa1.setText("NA");
        add(txCUBa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 130, -1, -1));

        txCUBa2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCUBa2.setForeground(new java.awt.Color(204, 204, 204));
        txCUBa2.setText("NA");
        add(txCUBa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 180, -1, -1));

        txCanBa1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCanBa1.setForeground(new java.awt.Color(204, 204, 204));
        txCanBa1.setText("NA");
        add(txCanBa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 130, -1, -1));

        txCanBa2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCanBa2.setForeground(new java.awt.Color(204, 204, 204));
        txCanBa2.setText("NA");
        add(txCanBa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 180, -1, -1));

        txCpBa1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCpBa1.setForeground(new java.awt.Color(204, 204, 204));
        txCpBa1.setText("NA");
        add(txCpBa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 130, -1, -1));

        txCpBa2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txCpBa2.setForeground(new java.awt.Color(204, 204, 204));
        txCpBa2.setText("NA");
        add(txCpBa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 180, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 970, 10));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 10, 60));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 10, 80));

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 40, 10, 80));

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 40, 10, 80));

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 40, 10, 80));

        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(36, 47, 65));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("El costo total de mezcla de básicos con la formulación optimizada es:");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextArea1.setDisabledTextColor(new java.awt.Color(36, 47, 65));
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 250, 70));

        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(36, 47, 65));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Costo por      básico\n   (USD)");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextArea2.setDisabledTextColor(new java.awt.Color(36, 47, 65));
        jScrollPane2.setViewportView(jTextArea2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 40, 100, 80));

        txCostMez2.setFont(new java.awt.Font("Century Gothic", 2, 24)); // NOI18N
        txCostMez2.setForeground(new java.awt.Color(204, 204, 204));
        txCostMez2.setText("NA");
        add(txCostMez2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        txtValFin.setFont(new java.awt.Font("Century Gothic", 2, 24)); // NOI18N
        txtValFin.setForeground(new java.awt.Color(204, 204, 204));
        txtValFin.setText("NA");
        add(txtValFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Ahorro al optimizar:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, -1, -1));

        txCostMez1.setFont(new java.awt.Font("Century Gothic", 2, 24)); // NOI18N
        txCostMez1.setForeground(new java.awt.Color(204, 204, 204));
        txCostMez1.setText("NA");
        add(txCostMez1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        jScrollPane4.setBorder(null);
        jScrollPane4.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(36, 47, 65));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("El costo total de mezcla de básicos sin optimizar la formulación es:");
        jTextArea4.setWrapStyleWord(true);
        jTextArea4.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextArea4.setDisabledTextColor(new java.awt.Color(36, 47, 65));
        jScrollPane4.setViewportView(jTextArea4);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 250, 70));

        jScrollPane3.setBorder(null);
        jScrollPane3.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(36, 47, 65));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Básicos Intercambiables");
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextArea3.setDisabledTextColor(new java.awt.Color(36, 47, 65));
        jScrollPane3.setViewportView(jTextArea3);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 670, 170, 70));

        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 400, 10, 80));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Básicos");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 60, -1, -1));

        txtNomBa1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtNomBa1.setForeground(new java.awt.Color(204, 204, 204));
        txtNomBa1.setText("NA");
        add(txtNomBa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, -1, -1));

        txtNomBa2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtNomBa2.setForeground(new java.awt.Color(204, 204, 204));
        txtNomBa2.setText("NA");
        add(txtNomBa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Nombre de básico");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, -1, -1));
        add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 970, 10));
        add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 750, 10));
        add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 750, 10));
        add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 750, 10));
        add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, 750, 10));
        add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 750, 10));

        jSeparator21.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 10, 80));

        jSeparator22.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 400, 10, 80));

        jScrollPane5.setBorder(null);
        jScrollPane5.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(36, 47, 65));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextArea5.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.setText("Fracción Masa");
        jTextArea5.setWrapStyleWord(true);
        jTextArea5.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextArea5.setDisabledTextColor(new java.awt.Color(36, 47, 65));
        jScrollPane5.setViewportView(jTextArea5);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 60, 140, 40));

        jScrollPane6.setBorder(null);
        jScrollPane6.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea6.setEditable(false);
        jTextArea6.setBackground(new java.awt.Color(36, 47, 65));
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextArea6.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea6.setLineWrap(true);
        jTextArea6.setRows(5);
        jTextArea6.setText(" Viscosidad\n cinemática\n(csT @ 100°C)");
        jTextArea6.setWrapStyleWord(true);
        jTextArea6.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextArea6.setDisabledTextColor(new java.awt.Color(36, 47, 65));
        jScrollPane6.setViewportView(jTextArea6);

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, 130, 70));

        jLabel42.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 204, 204));
        jLabel42.setText("Color:");
        add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 880, -1, -1));

        jLabel43.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(204, 204, 204));
        jLabel43.setText("Color");
        add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 430, -1, -1));

        txtInfoBas1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtInfoBas1.setForeground(new java.awt.Color(204, 204, 204));
        txtInfoBas1.setText("Información de básicos");
        add(txtInfoBas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, -1, -1));

        jSeparator23.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 10, 80));

        jSeparator24.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 10, 80));

        jSeparator25.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 650, 10, 330));

        txtViscoCin.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtViscoCin.setForeground(new java.awt.Color(204, 204, 204));
        txtViscoCin.setText("NA");
        add(txtViscoCin, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, -1, -1));

        txtViscoDin.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtViscoDin.setForeground(new java.awt.Color(204, 204, 204));
        txtViscoDin.setText("NA");
        add(txtViscoDin, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 510, -1, -1));

        txtColor.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtColor.setForeground(new java.awt.Color(204, 204, 204));
        txtColor.setText("NA");
        add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 510, -1, -1));

        txtVola.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtVola.setForeground(new java.awt.Color(204, 204, 204));
        txtVola.setText("NA");
        add(txtVola, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 510, -1, -1));

        txtViscoCin1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtViscoCin1.setForeground(new java.awt.Color(204, 204, 204));
        txtViscoCin1.setText("NA");
        add(txtViscoCin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 550, -1, -1));

        txtViscoDin1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtViscoDin1.setForeground(new java.awt.Color(204, 204, 204));
        txtViscoDin1.setText("NA");
        add(txtViscoDin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 550, -1, -1));

        txtColor1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtColor1.setForeground(new java.awt.Color(204, 204, 204));
        txtColor1.setText("NA");
        add(txtColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 550, -1, -1));

        txtVola1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtVola1.setForeground(new java.awt.Color(204, 204, 204));
        txtVola1.setText("NA");
        add(txtVola1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 550, -1, -1));

        txtViscoCin2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtViscoCin2.setForeground(new java.awt.Color(204, 204, 204));
        txtViscoCin2.setText("NA");
        add(txtViscoCin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 590, -1, -1));

        txtViscoDin2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtViscoDin2.setForeground(new java.awt.Color(204, 204, 204));
        txtViscoDin2.setText("NA");
        add(txtViscoDin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 590, -1, -1));

        txtColor2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtColor2.setForeground(new java.awt.Color(204, 204, 204));
        txtColor2.setText("NA");
        add(txtColor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 590, -1, -1));

        txtVola2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtVola2.setForeground(new java.awt.Color(204, 204, 204));
        txtVola2.setText("NA");
        add(txtVola2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 590, -1, -1));

        jSeparator26.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 40, 10, 80));

        jScrollPane7.setBorder(null);
        jScrollPane7.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea7.setEditable(false);
        jTextArea7.setBackground(new java.awt.Color(36, 47, 65));
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextArea7.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea7.setLineWrap(true);
        jTextArea7.setRows(5);
        jTextArea7.setText("Costo unitario\n   (USD/kg)");
        jTextArea7.setWrapStyleWord(true);
        jTextArea7.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextArea7.setDisabledTextColor(new java.awt.Color(36, 47, 65));
        jScrollPane7.setViewportView(jTextArea7);

        add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 50, 140, 70));

        txtFracMa1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtFracMa1.setForeground(new java.awt.Color(204, 204, 204));
        txtFracMa1.setText("NA");
        add(txtFracMa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 130, -1, -1));

        txtFracMa2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtFracMa2.setForeground(new java.awt.Color(204, 204, 204));
        txtFracMa2.setText("NA");
        add(txtFracMa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 180, -1, -1));

        txtViscoCin3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtViscoCin3.setForeground(new java.awt.Color(204, 204, 204));
        txtViscoCin3.setText("Optimizado:");
        add(txtViscoCin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, -1, -1));

        txtViscoCin4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtViscoCin4.setForeground(new java.awt.Color(204, 204, 204));
        txtViscoCin4.setText("Programa:");
        add(txtViscoCin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 550, -1, -1));

        txtViscoCin5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtViscoCin5.setForeground(new java.awt.Color(204, 204, 204));
        txtViscoCin5.setText("Formulación:");
        add(txtViscoCin5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 590, -1, -1));

        txtInfoBas2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtInfoBas2.setForeground(new java.awt.Color(204, 204, 204));
        txtInfoBas2.setText("diff 1x2");
        add(txtInfoBas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 220, -1, -1));

        jScrollPane8.setBorder(null);
        jScrollPane8.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea8.setEditable(false);
        jTextArea8.setBackground(new java.awt.Color(36, 47, 65));
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextArea8.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea8.setLineWrap(true);
        jTextArea8.setRows(5);
        jTextArea8.setText("x1 Programa");
        jTextArea8.setWrapStyleWord(true);
        jTextArea8.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextArea8.setDisabledTextColor(new java.awt.Color(36, 47, 65));
        jScrollPane8.setViewportView(jTextArea8);

        add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 260, 130, 30));
        add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 220, 10));
        add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 760, 10));

        jSeparator29.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 10, 50));

        jScrollPane9.setBorder(null);
        jScrollPane9.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea9.setEditable(false);
        jTextArea9.setBackground(new java.awt.Color(36, 47, 65));
        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextArea9.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea9.setLineWrap(true);
        jTextArea9.setRows(5);
        jTextArea9.setText("x2 Programa");
        jTextArea9.setWrapStyleWord(true);
        jTextArea9.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextArea9.setDisabledTextColor(new java.awt.Color(36, 47, 65));
        jScrollPane9.setViewportView(jTextArea9);

        add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 260, 130, 30));

        jSeparator31.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 250, 10, 50));

        jSeparator32.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 250, 10, 50));

        txtx1Form.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtx1Form.setForeground(new java.awt.Color(204, 204, 204));
        txtx1Form.setText("NA");
        add(txtx1Form, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, -1, -1));

        txtx1Prog.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtx1Prog.setForeground(new java.awt.Color(204, 204, 204));
        txtx1Prog.setText("NA");
        add(txtx1Prog, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 320, -1, -1));

        txtx2Form.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtx2Form.setForeground(new java.awt.Color(204, 204, 204));
        txtx2Form.setText("NA");
        add(txtx2Form, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 320, -1, -1));

        txtx2Prog.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtx2Prog.setForeground(new java.awt.Color(204, 204, 204));
        txtx2Prog.setText("NA");
        add(txtx2Prog, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 320, -1, -1));

        jSeparator33.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 250, 10, 50));

        jSeparator34.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 250, 10, 50));

        jScrollPane10.setBorder(null);
        jScrollPane10.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea10.setEditable(false);
        jTextArea10.setBackground(new java.awt.Color(36, 47, 65));
        jTextArea10.setColumns(20);
        jTextArea10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextArea10.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea10.setLineWrap(true);
        jTextArea10.setRows(5);
        jTextArea10.setText("x1 Fórmula");
        jTextArea10.setWrapStyleWord(true);
        jTextArea10.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextArea10.setDisabledTextColor(new java.awt.Color(36, 47, 65));
        jScrollPane10.setViewportView(jTextArea10);

        add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 110, 30));
        add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 760, 10));

        jScrollPane11.setBorder(null);
        jScrollPane11.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane11.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane11.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea11.setEditable(false);
        jTextArea11.setBackground(new java.awt.Color(36, 47, 65));
        jTextArea11.setColumns(20);
        jTextArea11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextArea11.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea11.setLineWrap(true);
        jTextArea11.setRows(5);
        jTextArea11.setText("x2 Fórmula");
        jTextArea11.setWrapStyleWord(true);
        jTextArea11.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextArea11.setDisabledTextColor(new java.awt.Color(36, 47, 65));
        jScrollPane11.setViewportView(jTextArea11);

        add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 260, 110, 30));

        jSeparator35.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 400, 10, 80));

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo1.setName(""); // NOI18N
        add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 760, -1, -1));

        txtInfoBas3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtInfoBas3.setForeground(new java.awt.Color(204, 204, 204));
        txtInfoBas3.setText("Información de producto");
        add(txtInfoBas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 370, -1, -1));

        jScrollPane12.setBorder(null);
        jScrollPane12.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane12.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane12.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea12.setEditable(false);
        jTextArea12.setBackground(new java.awt.Color(36, 47, 65));
        jTextArea12.setColumns(20);
        jTextArea12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextArea12.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea12.setLineWrap(true);
        jTextArea12.setRows(5);
        jTextArea12.setText(" Viscosidad\n  dinámica \n       (cP)");
        jTextArea12.setWrapStyleWord(true);
        jTextArea12.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextArea12.setDisabledTextColor(new java.awt.Color(36, 47, 65));
        jScrollPane12.setViewportView(jTextArea12);

        add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 410, 130, 70));
    }// </editor-fold>//GEN-END:initComponents
    static String readFile(String path, Charset encoding) throws IOException 
    {
        //System.out.println(path);
      byte[] encoded = Files.readAllBytes(Paths.get(path));
      return new String(encoded, encoding);
    }
    
//    private void cargaEstado(){
//       // System.out.println(path);
//        try {
//          String aux = readFile(path+"\\producto.txt",Charset.defaultCharset());
//          estado = aux.split(";");
//        }
//        catch(IOException e){
//            System.out.println("Error al leer archivo");
//        }
//        
//    
//    }
    private void btnCalculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculaActionPerformed
        // TODO add your handling code here:
        System.out.println(combo.getSelectedItem());
        txAviso.setVisible(true);
        
        //Vaciamos las etiquetas
        for (JLabel infProd1 : infProd) {
            infProd1.setText("");
        }
        
        for (JLabel dif1x21 : dif1x2) {
            dif1x21.setText("");
        }
        
        for (JLabel infBa : infBas) {
            infBa.setText("");
        }
        
        for (JLabel form1 : form) {
            form1.setText("");
        }
        
        
        txCostMez1.setText("");
        txCostMez2.setText("");
        txtValFin.setText("");
        
    }//GEN-LAST:event_btnCalculaActionPerformed

    private void comboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txAviso.setVisible(true);
            System.out.println("set visible");
               // TODO add your handling code here:
        
        
        }
            
    }//GEN-LAST:event_comboKeyPressed

    private void txAvisoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txAvisoComponentShown
        // TODO add your handling code here:
        String froz = "placeholder";
        
        System.out.println(combo.getSelectedItem());
        if(rbFroz.isSelected()){
            froz = "FROZEN";
        }
        
        try{ 
            Runtime rt = Runtime.getRuntime();
            System.out.println(path);
            Process pr = rt.exec("julia mezclas.jl "+combo.getSelectedItem() + " " +txtDemanda.getText() + " " + froz);
                
               InputStream is = pr.getInputStream();
               String line;
               BufferedReader reader = new BufferedReader(new InputStreamReader(is));
               
               while((line = reader.readLine()) != null){
                   System.out.print(line);
               }
      
        ArrayList<String[]> temp = Utils.getDataFromCsv("resultados_mezclas",true);
        
        txtViscoCin.setText(temp.get(9)[0]);
        txtViscoDin.setText(temp.get(0)[0]);
        txtColor.setText(temp.get(3)[0]);
        txtVola.setText(temp.get(6)[0]);
        txtViscoCin1.setText(temp.get(10)[0]);
        txtViscoDin1.setText(temp.get(1)[0]);
        txtColor1.setText(temp.get(4)[0]);
        txtVola1.setText(temp.get(7)[0]);
        txtViscoCin2.setText(temp.get(11)[0]);
        txtViscoDin2.setText(temp.get(2)[0]);
        txtColor2.setText(temp.get(5)[0]);
        txtVola2.setText(temp.get(8)[0]);

        temp = Utils.getDataFromCsv("dif_formulacion_realidad",true);
        
        for(int i=0;i<4;i++){
            dif1x2[i].setText(temp.get(0)[i]);
        }
        
        temp = Utils.getDataFromCsv("basicos_optimizados",true);
        
        txtNomBa1.setText(temp.get(0)[0]);
        txBa1.setText(temp.get(2)[0]);
        txtFracMa1.setText(temp.get(4)[0]);
        txCUBa1.setText(temp.get(6)[0]);
        txCanBa1.setText(temp.get(8)[0]);
        txCpBa1.setText(temp.get(10)[0]);
        txtNomBa2.setText(temp.get(1)[0]);
        txBa2.setText(temp.get(3)[0]);
        txtFracMa2.setText(temp.get(5)[0]);
        txCUBa2.setText(temp.get(7)[0]);
        txCanBa2.setText(temp.get(9)[0]);
        txCpBa2.setText(temp.get(11)[0]);
        
        temp = Utils.getDataFromCsv("costo_sin_optimizar",true);
        
        txCostMez1.setText(temp.get(0)[0]);
        
        temp = Utils.getDataFromCsv("costo_optimizado",true);
        
        txCostMez2.setText(temp.get(0)[0]);
        
        temp = Utils.getDataFromCsv("dif_cost_optimizado",true);
        
        txtValFin.setText(temp.get(0)[0]);
        
        temp = Utils.getDataFromCsv("producto", true);
        
        txtCodProd.setText(temp.get(2)[0]);
        txLinea.setText(temp.get(0)[0]);
        txGrado.setText(temp.get(1)[0]);
        txB1n.setText(temp.get(4)[0]);
        txB1c.setText(temp.get(3)[0]);
        txB2n.setText(temp.get(7)[0]);
        txB2c.setText(temp.get(6)[0]);
        txB1x.setText(temp.get(5)[0]);
        txB2x.setText(temp.get(8)[0]);
        txTemp.setText(temp.get(10)[0]);
        txVol.setText(temp.get(13)[0]);
        txCst.setText(temp.get(9)[0]);
        txColor.setText(temp.get(12)[0]);
        txCp.setText(temp.get(11)[0]);
        txCpM1.setText(temp.get(14)[0]);
        
        ArrayList<String>itemsCombo = Utils.generaCol("basicos_intercambiables", 1);
        Collections.sort(itemsCombo);
        
        combo1.removeAllItems();
        
        for(String s : itemsCombo)
            combo1.addItem(s);
        
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
        txAviso.setVisible(false);
    }//GEN-LAST:event_txAvisoComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcula;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JLabel lbDemanda;
    private javax.swing.JRadioButton rbFroz;
    private javax.swing.JLabel txAviso;
    private javax.swing.JLabel txB1c;
    private javax.swing.JLabel txB1n;
    private javax.swing.JLabel txB1x;
    private javax.swing.JLabel txB2c;
    private javax.swing.JLabel txB2n;
    private javax.swing.JLabel txB2x;
    private javax.swing.JLabel txBa1;
    private javax.swing.JLabel txBa2;
    private javax.swing.JLabel txCUBa1;
    private javax.swing.JLabel txCUBa2;
    private javax.swing.JLabel txCanBa1;
    private javax.swing.JLabel txCanBa2;
    private javax.swing.JLabel txColor;
    private javax.swing.JLabel txCostMez1;
    private javax.swing.JLabel txCostMez2;
    private javax.swing.JLabel txCp;
    private javax.swing.JLabel txCpBa1;
    private javax.swing.JLabel txCpBa2;
    private javax.swing.JLabel txCpM;
    private javax.swing.JLabel txCpM1;
    private javax.swing.JLabel txCst;
    private javax.swing.JLabel txGrado;
    private javax.swing.JLabel txLinea;
    private javax.swing.JLabel txTemp;
    private javax.swing.JLabel txVol;
    private javax.swing.JLabel txtCodProd;
    private javax.swing.JLabel txtColor;
    private javax.swing.JLabel txtColor1;
    private javax.swing.JLabel txtColor2;
    private javax.swing.JTextField txtDemanda;
    private javax.swing.JLabel txtFracMa1;
    private javax.swing.JLabel txtFracMa2;
    private javax.swing.JLabel txtInfoBas1;
    private javax.swing.JLabel txtInfoBas2;
    private javax.swing.JLabel txtInfoBas3;
    private javax.swing.JLabel txtNomBa1;
    private javax.swing.JLabel txtNomBa2;
    private javax.swing.JLabel txtValFin;
    private javax.swing.JLabel txtViscoCin;
    private javax.swing.JLabel txtViscoCin1;
    private javax.swing.JLabel txtViscoCin2;
    private javax.swing.JLabel txtViscoCin3;
    private javax.swing.JLabel txtViscoCin4;
    private javax.swing.JLabel txtViscoCin5;
    private javax.swing.JLabel txtViscoDin;
    private javax.swing.JLabel txtViscoDin1;
    private javax.swing.JLabel txtViscoDin2;
    private javax.swing.JLabel txtVola;
    private javax.swing.JLabel txtVola1;
    private javax.swing.JLabel txtVola2;
    private javax.swing.JLabel txtx1Form;
    private javax.swing.JLabel txtx1Prog;
    private javax.swing.JLabel txtx2Form;
    private javax.swing.JLabel txtx2Prog;
    // End of variables declaration//GEN-END:variables
}
